# Generated by Django 3.1.2 on 2020-10-11 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ipam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=64)),
                ('netbox_cluster_id', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('config', models.JSONField()),
                ('state', models.JSONField()),
                ('status', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('host_cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vms.hostcluster')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipam.network')),
            ],
        ),
        migrations.CreateModel(
            name='HostClusterNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('host_cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vms.hostcluster')),
            ],
        ),
    ]
