# Generated by Django 3.1.2 on 2020-10-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vm',
            name='vm_id',
            field=models.IntegerField(null=True),
        ),
    ]
