# Generated by Django 3.1.2 on 2020-12-04 22:30

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ipam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VmTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('config', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipam.environment')),
            ],
        ),
        migrations.CreateModel(
            name='Vm',
            fields=[
                ('id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('config', models.JSONField()),
                ('state', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipam.environment')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipam.network')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vm.vmtemplate')),
            ],
        ),
    ]
