# Generated by Django 3.1.2 on 2021-01-30 21:17

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ipam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VmTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('config', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipam.platform')),
            ],
        ),
        migrations.CreateModel(
            name='Vm',
            fields=[
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('config', models.JSONField()),
                ('state', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(default=None, null=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipam.network')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipam.platform')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vm.vmtemplate')),
            ],
        ),
    ]
