# Generated by Django 3.1.4 on 2020-12-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='deleted',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
